name: First workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greetings
        run: echo "hello universe"
      - name: Print bye
        run: echo 'done bye'
      
